### ISSUE TITLE
Displaying the wrong error: `no-missing-end-of-source-newline`

### ISSUE THREAD

**Issue by peterlobster** [sublimelsp/LSP-stylelint#28] opened 2022-05-12 20:05 UTC
I'm having a strange issue. I've noticed that when I open my project with Sublime and LSP-stylelint, I get the following error when I save a document...

![Screenshot from 2022-05-12 12-34-54](https://user-images.githubusercontent.com/38382145/168155328-9aa18929-bc28-4a1d-ad5c-8886a133554b.png)

My (pretty basic) `.stylelintrc` is as follows...

```json
{
  "extends": "stylelint-config-recommended",
}
```

Now, when I open this project with _VSCodium_ with the stylelint extension installed, and it reported no such problem.
 
I did read that it may be needed to disable `no-missing-end-of-source-newline` (https://github.com/stylelint/stylelint/issues/3410#issuecomment-399658964), however, I don't think that's the case here since _VSCodium_ does not display this error.

**Comment by peterlobster** [comment] 2022-05-12 20:13
FWIW, even if you change the `.stylelintrc` file to...

```json
{
  "extends": "stylelint-config-recommended",
  "rules": {
    "no-missing-end-of-source-newline": null
  }
}
```

It still displays the error.

**Comment by rchl** [comment] 2022-05-13 07:08
Would need a project that reproduces to test.

**Comment by rchl** [comment] 2022-05-13 14:50
In that case there is this vscode-specific configuration that might be making it work in there: https://github.com/Mountain-Cabins-Utah/Website/blob/master/.vscode/settings.json

**Comment by ran-dall** [comment] 2022-05-13 18:13
> In that case there is this vscode-specific configuration that might be making it "work" in there: [https://github.com/Mountain-Cabins-Utah/Website/blob/master/.vscode/settings.json](https://github.com/Mountain-Cabins-Utah/Website/blob/master/.vscode/settings.json?rgh-link-date=2022-05-13T14%3A50%3A36Z)

That was just done to disable the built-in CSS LSP to avoid some double suggestions (it's recommended (but optional) by the Stylelint plugin). It still works fine if you re-enable it. If you'd like, I can commit it and send it you.

**Comment by rchl** [comment] 2022-05-14 20:28
In which file is it supposed to reproduce in that project and after doing what actions? I can only see some css files there and I can't see the issue reported here.

**Comment by ran-dall** [comment] 2022-05-15 00:21
@rchl Pretty much any CSS files should display the error, as long as the LSP is running.

**Comment by rchl** [comment] 2022-05-15 11:02
I don't see that:

![Screenshot 2022-05-15 at 13 02 20](https://user-images.githubusercontent.com/153197/168469469-becce9e5-7ad5-4668-8807-b44685d2d644.png)

**Comment by rchl** [comment] 2022-05-15 11:04
You could provide output of `LSP: Troubleshoot Server` which might help to see what's wrong for you.

**Comment by ran-dall** [comment] 2022-05-15 12:10
```
# Troubleshooting: LSP-stylelint
## Version
 - LSP: 1.16.2
 - Sublime Text: 4126
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh
/usr/bin/node "/home/randall/.cache/sublime-text/Package Storage/LSP-stylelint/14.19.0/language-server/dist/start-server.js" --stdio
```
 - selector
```
source.css | source.scss | source.less | source.pcss | source.postcss | text.html.vue
```
 - priority_selector
```
(source.scss)|(source.less)|(source.css)|(text.html.vue)
```
 - init_options
```json
{}
```
 - settings
```json
{
  "stylelint": {
    "codeAction": {
      "disableRuleComment": {
        "location": "separateLine"
      }
    }, 
    "config": null, 
    "configBasedir": "", 
    "configFile": "", 
    "configOverrides": null, 
    "customSyntax": "", 
    "enable": true, 
    "ignoreDisables": false, 
    "packageManager": "npm", 
    "reportInvalidScopeDisables": false, 
    "reportNeedlessDisables": false, 
    "snippet": [
      "css", 
      "less", 
      "postcss"
    ], 
    "stylelintPath": "", 
    "syntax": "", 
    "validate": [
      "css", 
      "less", 
      "postcss"
    ]
  }
}
```
 - env
```json
{
  "PATH": "/usr/bin:/usr/bin:"
}
```

## Active view
 - File name
```
/home/randall/Desktop/MCU/src/styles/style.css
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": true, 
  "syntax": "Packages/CSS/CSS.sublime-syntax"
}
```
 - base scope
```
source.css
```

## Project / Workspace
 - folders
```json
[
  "/home/randall/Desktop/MCU"
]
```
 - is project: True
 - project data:
```json
{
  "folders": [
    {
      "path": "."
    }
  ], 
  "settings": {
    "LSP": {
      "LSP-css": {
        "enabled": false
      }
    }
  }
}
```

## LSP configuration

```json
{
  "lsp_format_on_save": true
}
```
## System PATH
 - /usr/local/sbin
 - /usr/local/bin
 - /usr/sbin
 - /usr/bin
 - /sbin
 - /bin
 - /opt/bin
 - /usr/lib/llvm/13/bin
 - /usr/lib/llvm/12/bin
 - /opt/cuda/bin
 ```

**Comment by ran-dall** [comment] 2022-05-15 12:12
@rchl I get it unconditionally every time I save.

**Comment by rchl** [comment] 2022-05-15 20:03
So this triggers on formatting the file (`LSP: Format File`). You have `lsp_format_on_save` enabled which is not enabled by default so you see it on save.

Appears to be due to ST LSP client sending more formatting options than VSCode.

We are sending:

```
textDocument/formatting(3): {'textDocument': {'uri': 'file:///usr/local/workspace/temp/Website/src/styles/style.css'}, 'workDoneToken': 'wd3', 'options': {'insertFinalNewline': True, 'trimTrailingWhitespace': False, 'trimFinalNewlines': True, 'tabSize': 4, 'insertSpaces': False}}
```

while VSCode only sends `tabSize` and `insertSpaces`.

The options that we are sending are new in `3.15.0` version of the LSP spec but those are still per spec so it seems like something that should be fixed in https://github.com/stylelint/vscode-stylelint/

**Comment by rchl** [comment] 2022-05-15 20:23
Created an issue in https://github.com/stylelint/vscode-stylelint/issues/398.

**Comment by ran-dall** [comment] 2022-05-15 22:40
@rchl Fair enough. Thank you for looking into it. However, shouldn't that be turned off when you have the option `"no-descending-specificity": null` disabled on `.stylelintrc.json`?

**Comment by rchl** [comment] 2022-05-16 07:22
How is `no-descending-specificity` related to the being a trailing newline or not?

But no, it appears that `vscode-stylelint` doesn't concern itself with the `.stylelintrc.json` configuration. It just calls `stylelint` API with some rule overrides and `stylelint` itself reads configuration.

**Comment by ran-dall** [comment] 2022-05-16 20:55
> How is no-descending-specificity related to there being a trailing newline or not?
 
Sorry copied the wrong line. It was `no-missing-end-of-source-newline: null`.

Anyways, thank you for your explanation and support.

**Comment by rchl** [comment] 2022-05-16 21:05
Still, `no-missing-end-of-source-newline` doesn't seem related to `no-descending-specificity`. It's just about whether there is a trailing newline at the end of the file.

**Comment by ran-dall** [comment] 2022-05-16 21:29
> Still, no-missing-end-of-source-newline doesn't seem related to no-descending-specificity. 

It's not. It's my mistake.

Also, to clarify my understanding (and maybe for the record for other users later), the change in `no-missing-end-of-source-newline` was due to the reasons outlined here: https://github.com/stylelint/stylelint/issues/3410#issuecomment-399658964. (tl;dr: the change was brought for compatibility reasons for syntax located within `<style>` tags.)

Therefore, is the fix what was made in your PR and your issue upstream? Or how would one go about addressing this properly?

**Comment by rchl** [comment] 2022-05-17 11:11
My fix upstream is to not pass a `false` value for `no-missing-end-of-source-newline` or `no-eol-whitespace` rules when the formatting action asks to have those disabled. `false` is an invalid value and triggers the error dialog mentioned in the initial comment.

As far as how those rules affect files like *.vue is a separate discussion.

**Comment by ran-dall** [comment] 2022-05-21 14:27
@rchl Sorry got caught up on working on Gentoo the last few days. 

Right on. Thank you for the explanation. So if your upstream fix doesn't this issue, and it's supposed to not parse `.stylelintrc`, then how would you go about silencing this error? I'm assuming it probably would be in the settings?

**Comment by rchl** [comment] 2022-05-21 15:26
My upstream fix fixes this issue (as reported in the initial content).

Once the upstream fix is included here then you can test your other problem and report a separate issue about it.

**Comment by ran-dall** [comment] 2022-05-23 17:44
@rchl I think that's my problem though, cause my files are `.css` files that are configured as PostCSS; or is that (the PostCSS syntax option) the problem?

**Comment by ran-dall** [comment] 2022-05-23 17:45
@rchl Sounds good.

**Comment by ran-dall** [comment] 2022-05-23 17:46
@peterlobster Did our discussion address your concern? Can we close this if it did?

**Closed** 2022-05-25 01:45 UTC

**Comment by rchl** [comment] 2022-08-16 06:59
Released https://github.com/sublimelsp/LSP-stylelint/releases/tag/2.0.1 with the fix that should be available in few hours from now.
